window.env = {
  PUBLIC_BACKEND_URL: process.env.PUBLIC_BACKEND_URL || process.env.NEXT_PUBLIC_BACKEND_URL,
  PUBLIC_SUPABASE_URL: process.env.PUBLIC_SUPABASE_URL || process.env.NEXT_PUBLIC_SUPABASE_URL,
  PUBLIC_SUPABASE_ANON_KEY: process.env.PUBLIC_SUPABASE_ANON_KEY || process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY,
};
